// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ContactuspageDocumentDataSlicesSlice = ContactUsSlice;

/**
 * Content for ContactUsPage documents
 */
interface ContactuspageDocumentData {
  /**
   * Title field in *ContactUsPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactuspage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *ContactUsPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contactuspage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactuspageDocumentDataSlicesSlice> /**
   * Meta Title field in *ContactUsPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contactuspage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ContactUsPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contactuspage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ContactUsPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactuspage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ContactUsPage document from Prismic
 *
 * - **API ID**: `contactuspage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactuspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactuspageDocumentData>,
    "contactuspage",
    Lang
  >;

type FindStoresDocumentDataSlicesSlice = FindStoresSlice;

/**
 * Content for Find Stores documents
 */
interface FindStoresDocumentData {
  /**
   * Slice Zone field in *Find Stores*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FindStoresDocumentDataSlicesSlice> /**
   * Meta Title field in *Find Stores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: find_stores.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Find Stores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: find_stores.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Find Stores*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Find Stores document from Prismic
 *
 * - **API ID**: `find_stores`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FindStoresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FindStoresDocumentData>,
    "find_stores",
    Lang
  >;

type FizzifunpageDocumentDataSlicesSlice = RulesSlice | LandingSliceSlice;

/**
 * Content for FizziFunPage documents
 */
interface FizzifunpageDocumentData {
  /**
   * Title field in *FizziFunPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fizzifunpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *FizziFunPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: fizzifunpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FizzifunpageDocumentDataSlicesSlice> /**
   * Meta Title field in *FizziFunPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: fizzifunpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FizziFunPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: fizzifunpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FizziFunPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fizzifunpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FizziFunPage document from Prismic
 *
 * - **API ID**: `fizzifunpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FizzifunpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FizzifunpageDocumentData>,
    "fizzifunpage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BigTextSlice
  | AlternateTextSliceSlice
  | CarouselSlice
  | SkyDiveSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface PageDocumentData {
  /**
   * Title field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ContactuspageDocument
  | FindStoresDocument
  | FizzifunpageDocument
  | PageDocument;

/**
 * Item in *AlternateText → Default → Primary → Text Group*
 */
export interface AlternateTextSliceSliceDefaultPrimaryTextGroupItem {
  /**
   * Heading field in *AlternateText → Default → Primary → Text Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading for AlternativeText
   * - **API ID Path**: alternate_text_slice.default.primary.text_group[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *AlternateText → Default → Primary → Text Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body for AlternativeText
   * - **API ID Path**: alternate_text_slice.default.primary.text_group[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *AlternateText → Default → Primary*
 */
export interface AlternateTextSliceSliceDefaultPrimary {
  /**
   * Text Group field in *AlternateText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_text_slice.default.primary.text_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  text_group: prismic.GroupField<
    Simplify<AlternateTextSliceSliceDefaultPrimaryTextGroupItem>
  >;
}

/**
 * Default variation for AlternateText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateTextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateTextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlternateText*
 */
type AlternateTextSliceSliceVariation = AlternateTextSliceSliceDefault;

/**
 * AlternateText Shared Slice
 *
 * - **API ID**: `alternate_text_slice`
 * - **Description**: AlternateTextSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateTextSliceSlice = prismic.SharedSlice<
  "alternate_text_slice",
  AlternateTextSliceSliceVariation
>;

/**
 * Default variation for BigText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BigText*
 */
type BigTextSliceVariation = BigTextSliceDefault;

/**
 * BigText Shared Slice
 *
 * - **API ID**: `big_text`
 * - **Description**: BigText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigTextSlice = prismic.SharedSlice<
  "big_text",
  BigTextSliceVariation
>;

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Heading field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading for the carousel
   * - **API ID Path**: carousel.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Price Copy field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.price_copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  price_copy: prismic.RichTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Item in *ContactUs → Default → Primary → Social Links*
 */
export interface ContactUsSliceDefaultPrimarySocialLinksItem {
  /**
   * Name field in *ContactUs → Default → Primary → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.social_links[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * URL field in *ContactUs → Default → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL for ContactUs page
   * - **API ID Path**: contact_us.default.primary.social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ContactUs → Default → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * Heading field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Heading for ContactUs page
   * - **API ID Path**: contact_us.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Address field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Address for ContactUs page
   * - **API ID Path**: contact_us.default.primary.address
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;

  /**
   * Email field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email for ContactUs page
   * - **API ID Path**: contact_us.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact number for ContactUs page
   * - **API ID Path**: contact_us.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Social Links field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<ContactUsSliceDefaultPrimarySocialLinksItem>
  >;

  /**
   * Blob color field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Blob color in hex for ContactUs page
   * - **API ID Path**: contact_us.default.primary.blob_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  blob_color: prismic.ColorField;

  /**
   * Background Wave field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact_us.default.primary.background_wave
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  background_wave: prismic.BooleanField;
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault;

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSlice = prismic.SharedSlice<
  "contact_us",
  ContactUsSliceVariation
>;

/**
 * Item in *FindStores → Default → Primary → StoresList*
 */
export interface FindStoresSliceDefaultPrimaryStoreslistItem {
  /**
   * City field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].city
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  city: prismic.KeyTextField;

  /**
   * Country field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].country
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  country: prismic.KeyTextField;

  /**
   * Address field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Latitude field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].latitude
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  latitude: prismic.NumberField;

  /**
   * Longitude field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].longitude
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  longitude: prismic.NumberField;

  /**
   * Featured field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: find_stores.default.primary.storeslist[].featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Store Image field in *FindStores → Default → Primary → StoresList*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[].store_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  store_image: prismic.ImageField<never>;
}

/**
 * Primary content in *FindStores → Default → Primary*
 */
export interface FindStoresSliceDefaultPrimary {
  /**
   * Title field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Show Globe field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: find_stores.default.primary.show_globe
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_globe: prismic.BooleanField;

  /**
   * Globe Theme field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Fizzi
   * - **API ID Path**: find_stores.default.primary.globe_theme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  globe_theme: prismic.SelectField<"Fizzi" | "Classic" | "Dark", "filled">;

  /**
   * Background Style field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Gradient
   * - **API ID Path**: find_stores.default.primary.background_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_style: prismic.SelectField<
    "Gradient" | "Solid" | "Image",
    "filled"
  >;

  /**
   * Background Image field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA Text field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * StoresList field in *FindStores → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: find_stores.default.primary.storeslist[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  storeslist: prismic.GroupField<
    Simplify<FindStoresSliceDefaultPrimaryStoreslistItem>
  >;
}

/**
 * Default variation for FindStores Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FindStoresSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FindStoresSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FindStores*
 */
type FindStoresSliceVariation = FindStoresSliceDefault;

/**
 * FindStores Shared Slice
 *
 * - **API ID**: `find_stores`
 * - **Description**: FindStores
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FindStoresSlice = prismic.SharedSlice<
  "find_stores",
  FindStoresSliceVariation
>;

/**
 * Default variation for FlavorLab Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FlavorLabSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FlavorLab*
 */
type FlavorLabSliceVariation = FlavorLabSliceDefault;

/**
 * FlavorLab Shared Slice
 *
 * - **API ID**: `flavor_lab`
 * - **Description**: FlavorLab
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FlavorLabSlice = prismic.SharedSlice<
  "flavor_lab",
  FlavorLabSliceVariation
>;

/**
 * Item in *FizziZoneGame → Default → Primary → Sprite List*
 */
export interface GameSliceDefaultPrimarySpriteListItem {
  /**
   * Sprite Name field in *FizziZoneGame → Default → Primary → Sprite List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.sprite_list[].sprite_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sprite_name: prismic.KeyTextField;

  /**
   * Sprite PNG field in *FizziZoneGame → Default → Primary → Sprite List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.sprite_list[].sprite_png
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sprite_png: prismic.ImageField<never>;

  /**
   * Points field in *FizziZoneGame → Default → Primary → Sprite List*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.sprite_list[].points
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  points: prismic.NumberField;

  /**
   * Spawn Chance field in *FizziZoneGame → Default → Primary → Sprite List*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.sprite_list[].spawn_chance
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  spawn_chance: prismic.NumberField;
}

/**
 * Primary content in *FizziZoneGame → Default → Primary*
 */
export interface GameSliceDefaultPrimary {
  /**
   * Background Gradient Start field in *FizziZoneGame → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.background_gradient_start
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_gradient_start: prismic.ColorField;

  /**
   * Background Gradient End field in *FizziZoneGame → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.background_gradient_end
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_gradient_end: prismic.ColorField;

  /**
   * Sprite List field in *FizziZoneGame → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.sprite_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sprite_list: prismic.GroupField<
    Simplify<GameSliceDefaultPrimarySpriteListItem>
  >;

  /**
   * Game Duration field in *FizziZoneGame → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: game.default.primary.game_duration
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  game_duration: prismic.NumberField;
}

/**
 * Default variation for FizziZoneGame Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GameSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FizziZoneGame*
 */
type GameSliceVariation = GameSliceDefault;

/**
 * FizziZoneGame Shared Slice
 *
 * - **API ID**: `game`
 * - **Description**: Game
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GameSlice = prismic.SharedSlice<"game", GameSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Main heading for hero
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * SubHeading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub heading for hero
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body for hero
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button_Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button text for hero button
   * - **API ID Path**: hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button link for hero button
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Cans Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cans_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cans_image: prismic.ImageField<never>;

  /**
   * Second Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second heading text
   * - **API ID Path**: hero.default.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  second_heading: prismic.RichTextField;

  /**
   * Second Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: second body text
   * - **API ID Path**: hero.default.primary.second_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  second_body: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *FizziZoneLanding → Default → Primary*
 */
export interface LandingSliceSliceDefaultPrimary {
  /**
   * Heading field in *FizziZoneLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * SubHeading field in *FizziZoneLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_slice.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * CTA Text field in *FizziZoneLanding → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_slice.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *FizziZoneLanding → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_slice.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for FizziZoneLanding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FizziZoneLanding*
 */
type LandingSliceSliceVariation = LandingSliceSliceDefault;

/**
 * FizziZoneLanding Shared Slice
 *
 * - **API ID**: `landing_slice`
 * - **Description**: LandingSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingSliceSlice = prismic.SharedSlice<
  "landing_slice",
  LandingSliceSliceVariation
>;

/**
 * Item in *FizziZoneRules → Default → Primary → Rules List*
 */
export interface RulesSliceDefaultPrimaryRulesListItem {
  /**
   * Rule Text field in *FizziZoneRules → Default → Primary → Rules List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.rules_list[].rule_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rule_text: prismic.KeyTextField;
}

/**
 * Primary content in *FizziZoneRules → Default → Primary*
 */
export interface RulesSliceDefaultPrimary {
  /**
   * Title field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Rules List field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.rules_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  rules_list: prismic.GroupField<
    Simplify<RulesSliceDefaultPrimaryRulesListItem>
  >;

  /**
   * Play Button Text field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.play_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  play_button_text: prismic.KeyTextField;

  /**
   * GameScreenHeading field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gamescreenheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gamescreenheading: prismic.KeyTextField;

  /**
   * GameScreenInfo field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gamescreeninfo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gamescreeninfo: prismic.KeyTextField;

  /**
   * GameScreenButtonText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gamescreenbuttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gamescreenbuttontext: prismic.KeyTextField;

  /**
   * Rules List Placeholder field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.rules_list_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rules_list_placeholder: prismic.RichTextField;

  /**
   * HUDScoreText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.hudscoretext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hudscoretext: prismic.RichTextField;

  /**
   * HUDTimeRemainingText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.hudtimeremainingtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hudtimeremainingtext: prismic.RichTextField;

  /**
   * HUDCreditText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.hudcredittext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hudcredittext: prismic.KeyTextField;

  /**
   * HUDCreditValue field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.hudcreditvalue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hudcreditvalue: prismic.KeyTextField;

  /**
   * GameOverHeading field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  gameoverheading: prismic.RichTextField;

  /**
   * GameOverTotalPointsText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameovertotalpointstext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameovertotalpointstext: prismic.KeyTextField;

  /**
   * GameOverRedeemablePointsText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverredeemablepointstext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameoverredeemablepointstext: prismic.KeyTextField;

  /**
   * GameOverConversionRate field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverconversionrate
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameoverconversionrate: prismic.KeyTextField;

  /**
   * GameOverTimePlayedText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameovertimeplayedtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameovertimeplayedtext: prismic.KeyTextField;

  /**
   * GameOverTimePlayedUnit field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameovertimeplayedunit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameovertimeplayedunit: prismic.KeyTextField;

  /**
   * GameOverLivesLeftText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverliveslefttext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameoverliveslefttext: prismic.KeyTextField;

  /**
   * GameOverPlayAgainText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverplayagaintext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameoverplayagaintext: prismic.KeyTextField;

  /**
   * GameOverFindStoresText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverfindstorestext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gameoverfindstorestext: prismic.KeyTextField;

  /**
   * GameOverFizziPointsText field in *FizziZoneRules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rules.default.primary.gameoverfizzipointstext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  gameoverfizzipointstext: prismic.RichTextField;
}

/**
 * Default variation for FizziZoneRules Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RulesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RulesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FizziZoneRules*
 */
type RulesSliceVariation = RulesSliceDefault;

/**
 * FizziZoneRules Shared Slice
 *
 * - **API ID**: `rules`
 * - **Description**: Rules
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RulesSlice = prismic.SharedSlice<"rules", RulesSliceVariation>;

/**
 * Primary content in *SkyDive → Default → Primary*
 */
export interface SkyDiveSliceDefaultPrimary {
  /**
   * Sentence field in *SkyDive → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sky_dive.default.primary.sentence
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sentence: prismic.KeyTextField;

  /**
   * Flavor field in *SkyDive → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Flavors of Fizzi to choose from
   * - **API ID Path**: sky_dive.default.primary.flavor
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  flavor: prismic.SelectField<
    "grape" | "blackCherry" | "strawberryLemonade" | "watermelon" | "lemonLime"
  >;
}

/**
 * Default variation for SkyDive Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkyDiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkyDiveSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SkyDive*
 */
type SkyDiveSliceVariation = SkyDiveSliceDefault;

/**
 * SkyDive Shared Slice
 *
 * - **API ID**: `sky_dive`
 * - **Description**: SkyDive
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SkyDiveSlice = prismic.SharedSlice<
  "sky_dive",
  SkyDiveSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactuspageDocument,
      ContactuspageDocumentData,
      ContactuspageDocumentDataSlicesSlice,
      FindStoresDocument,
      FindStoresDocumentData,
      FindStoresDocumentDataSlicesSlice,
      FizzifunpageDocument,
      FizzifunpageDocumentData,
      FizzifunpageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateTextSliceSlice,
      AlternateTextSliceSliceDefaultPrimaryTextGroupItem,
      AlternateTextSliceSliceDefaultPrimary,
      AlternateTextSliceSliceVariation,
      AlternateTextSliceSliceDefault,
      BigTextSlice,
      BigTextSliceVariation,
      BigTextSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimarySocialLinksItem,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      FindStoresSlice,
      FindStoresSliceDefaultPrimaryStoreslistItem,
      FindStoresSliceDefaultPrimary,
      FindStoresSliceVariation,
      FindStoresSliceDefault,
      FlavorLabSlice,
      FlavorLabSliceVariation,
      FlavorLabSliceDefault,
      GameSlice,
      GameSliceDefaultPrimarySpriteListItem,
      GameSliceDefaultPrimary,
      GameSliceVariation,
      GameSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LandingSliceSlice,
      LandingSliceSliceDefaultPrimary,
      LandingSliceSliceVariation,
      LandingSliceSliceDefault,
      RulesSlice,
      RulesSliceDefaultPrimaryRulesListItem,
      RulesSliceDefaultPrimary,
      RulesSliceVariation,
      RulesSliceDefault,
      SkyDiveSlice,
      SkyDiveSliceDefaultPrimary,
      SkyDiveSliceVariation,
      SkyDiveSliceDefault,
    };
  }
}
