// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_text_slice: dynamic(() => import("./AlternateText")),
  big_text: dynamic(() => import("./BigText")),
  carousel: dynamic(() => import("./Carousel")),
  contact_us: dynamic(() => import("./ContactUs")),
  find_stores: dynamic(() => import("./FindStores")),
  flavor_lab: dynamic(() => import("./FlavorLab")),
  hero: dynamic(() => import("./Hero")),
  landing_slice: dynamic(() => import("./FizziZoneLanding")),
  rules: dynamic(() => import("./FizziZoneRules")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
